###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: klikkk-abg-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=dtcworld2019
        - MYSQL_DATABASE=klikkkabg
        - MYSQL_USER=klikkkabg
        - MYSQL_PASSWORD=klikkkabg2019#
      ports:
        - "4730:3306"

    webserver:
      image: nginx:alpine
      container_name: klikkk-abg-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "4732:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: klikkk-abg-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: klikkk-abg-phpmyadmin
      links:
        - mysql
      environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
      restart: always
      ports:
        - 4735:80
      volumes:
        - /sessions
